baseurl = "/"
languageCode = "en-gb"

title = "TR's College Blog"
subtitle = "A place for college assignment tasks that must be submitted in blog form"
author = "Thomas Robinson"
copyright = "All Rights Reserved"

theme = "paper"
paginate = 999

[taxonomies]
tag = "tags"

[menu]
  [[menu.main]]
    identifier = "what"
    name = "What is This?"
    url = "/what/"

   [[menu.main]]
    identifier = "home"
    name = "Post List"
    url = "/"